{"name": "test03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <Test_inquire.Test_inquire object at 0x7f96f030fa00>\n\n    def test03(self):\n>       assert 1==2\nE       assert 1 == 2\n\ncase/series/Test_inquire.py:12: AssertionError"}, "start": 1651732977349, "stop": 1651732977349, "uuid": "4332aea0-a638-483d-ba81-e6be49b1c58d", "historyId": "ac7464321946c855d13df87a09557587", "testCaseId": "d2c3f5a2f734638ccd2a30d9ea3bcf2a", "fullName": "case.series.Test_inquire.Test_inquire#test03", "labels": [{"name": "parentSuite", "value": "case.series"}, {"name": "suite", "value": "Test_inquire"}, {"name": "subSuite", "value": "Test_inquire"}, {"name": "host", "value": "C02F63FFMD6R"}, {"name": "thread", "value": "28784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.series.Test_inquire"}]}